---
apiVersion: batch/v1
kind: Job
metadata:
  name: cloud-automated-test
spec:
  template:
    spec:
      containers:
      - image: cloud-automated-test
        name: cloud-automated-test
        env:
        - name: LOGGER_DEBUG
          value: "1"
        - name: COMPUTE_GRPC_ADDRESS
          value: "compute:9000"
        - name: IAM_GRPC_ADDRESS
          value: "iam:9001"
        - name: RDB_GRPC_ADDRESS
          value: "rdb:9002"
        - name: RESOURCEMANAGER_GRPC_ADDRESS
          value: "resourcemanager:9003"
      restartPolicy: Never
  backoffLimit: 3
